---
- name: Run FTL grader provision tasks
  when: ACTION | default('provision') in ('provision', 'create')
  ansible.builtin.include_tasks: provision.yml

- name: Run FTL grader multiuser provision tasks
  when:
    - ACTION | default('provision') in ('provision', 'create')
    - ocp4_workload_ftl_grader_user_count | int > 1
  ansible.builtin.include_tasks: provision-multiuser.yml
