---
galaxy_info:
  author: Red Hat Demo Platform
  description: Verify package is installed for FTL lab grading
  company: Red Hat
  license: Apache-2.0
  platforms:
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - grading
    - ftl
    - labs
    - validation
    - package
dependencies: []
